apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-import-job
  labels:
    app: mrp-oidc
spec:
  template:
    spec:
      containers:
      - name: keycloak-import
        image: 192.168.12.16:7005/agv-automated-guided-vehicles/agv-keycloak:latest
        command: ["kc.sh", "import", "--file=/opt/keycloak/data/import/realm.json"]
        volumeMounts:
        - name: keycloak-resources
          mountPath: /opt/keycloak/data/import
      restartPolicy: Never
      volumes:
      - name: keycloak-resources
        configMap:
          name: keycloak-resources-cm
  backoffLimit: 4
