apiVersion: v1
kind: Service
metadata:
  name: mrp-oidc-service
  labels:
    name: mrp-oidc-service
    app: mrp-oidc
spec:
  type: NodePort
  selector:
    name: mrp-oidc-pod
    app: mrp-oidc
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002